spring.application.name=conserta-ai
server.port=8080

# Ativacao de Virtual Threads do Java 21 (Project Loom)
spring.threads.virtual.enabled=true

# Banco de Dados H2 com Persistencia em Arquivo Local (Nao perde dados ao reiniciar)
spring.datasource.url=jdbc:h2:file:./data/consertaaidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# Habilitacao do Console Web do H2 Database em /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Documentacao OpenAPI Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
